# Generated by Django 3.1.2 on 2021-05-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewClickTransaction',
        ),
    ]
