# Generated by Django 3.2.8 on 2022-01-02 16:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_uz', models.CharField(max_length=300, null=True)),
                ('name_ru', models.CharField(max_length=300, null=True)),
                ('name_en', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('year', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('print_length', models.IntegerField()),
                ('form', multiselectfield.db.fields.MultiSelectField(choices=[('paper', 'PAPER'), ('pdf', 'PDF'), ('audio', 'AUDIO')], max_length=15)),
                ('tip', multiselectfield.db.fields.MultiSelectField(choices=[('discount', 'discount'), ('bestseller', 'bestseller'), ('recommended', 'recommended'), ('new', 'new'), ('best_prices', 'best_prices')], max_length=47)),
                ('paper_price', models.FloatField(blank=True, default=0, null=True)),
                ('paper_discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('paper_dic_price', models.FloatField(blank=True, default=0, null=True)),
                ('quantity', models.CharField(max_length=100)),
                ('audio_price', models.FloatField(blank=True, default=0, null=True)),
                ('audio_discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('audio_dic_price', models.FloatField(blank=True, default=0, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('pdf_price', models.FloatField(blank=True, default=0, null=True)),
                ('pdf_discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='')),
                ('pdf_dic_price', models.FloatField(blank=True, default=0, null=True)),
                ('book_view', models.IntegerField(blank=True, default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.authormodal')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='PublisherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publisher',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.bookmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'commets',
            },
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='category',
            field=models.ManyToManyField(blank=True, to='books.CategoryModel'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='languages',
            field=models.ManyToManyField(blank=True, to='books.LanguageModel'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.publishermodel'),
        ),
        migrations.CreateModel(
            name='AdminCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('com', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.commentmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin comment',
                'verbose_name_plural': 'Admin commets',
            },
        ),
    ]
