# Generated by Django 3.2.8 on 2021-11-01 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='real_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='book_view',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
