# Generated by Django 3.2.8 on 2021-12-09 13:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='audio_dic_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='audio_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='paper_dic_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='paper_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='pdf_dic_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='pdf_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='tip',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('discount', 'discount'), ('bestseller', 'bestseller'), ('recommended', 'recommended'), ('new', 'new'), ('best_prices', 'best_prices')], max_length=47),
        ),
    ]
