# Generated by Django 3.2.8 on 2021-12-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211230_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='category',
            field=models.ManyToManyField(blank=True, to='books.CategoryModel'),
        ),
    ]
