# Generated by Django 3.2.8 on 2021-11-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211101_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_view',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='real_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
