# Generated by Django 3.2.8 on 2021-11-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211101_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_view',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
