# Generated by Django 3.2.8 on 2021-12-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211211_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='post',
            new_name='book',
        ),
    ]
