# Generated by Django 3.2.8 on 2021-11-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookmodel_book_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='price',
            field=models.FloatField(),
        ),
    ]
