# Generated by Django 3.2.8 on 2021-11-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookmodel_book_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='publication_date',
            field=models.CharField(max_length=250),
        ),
    ]
