# Generated by Django 3.2.8 on 2021-12-13 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_alter_commentmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('com', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.commentmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin comment',
                'verbose_name_plural': 'Admin commets',
            },
        ),
    ]
