# Generated by Django 3.2.8 on 2021-12-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_extendeduserexample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUserExample',
        ),
    ]
