# Generated by Django 3.2.8 on 2021-12-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_extendeduserexample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='birthday',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
