# Generated by Django 3.2.8 on 2021-12-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211213_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='last_name',
        ),
    ]
