# Generated by Django 3.2.8 on 2021-12-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211213_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(choices=[('girl', 'girl'), ('boy', 'boy')], max_length=50),
        ),
    ]
