# Generated by Django 3.2.8 on 2021-12-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
