# Generated by Django 3.2.8 on 2022-02-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='pay',
            field=models.CharField(choices=[('processing', 'processing'), ('click', 'click'), ('payme', 'payme'), ('cancelled', 'cancelled')], default='processing', max_length=50),
        ),
    ]
