# Generated by Django 3.2.8 on 2021-12-18 04:59

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_id',
            field=models.CharField(blank=True, default=orders.models.create_new_ref_number, editable=False, max_length=10, unique=True),
        ),
    ]
