# Generated by Django 3.2.8 on 2021-12-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='pay',
            field=models.CharField(choices=[('click', 'click'), ('payme', 'payme')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
