# Generated by Django 3.2.8 on 2021-12-19 04:48

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_id',
            field=models.CharField(blank=True, default=orders.models.create_new_ref_number, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Tasdiqlash jarayonida', 'Tasdiqlash jarayonida'), ('Tastiqlandi', 'Tastiqlandi'), ("Buyurtma yo'lga chiqdi", "Buyurtma yo'lga chiqdi"), ('Buyurtma yetkazildi', 'Buyurtma yetkazildi')], default='Tasdiqlash jarayonida', max_length=100, null=True),
        ),
    ]
