# Generated by Django 3.2.8 on 2021-12-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='pay',
            field=models.CharField(choices=[('progress', 'progress'), ('click', 'click'), ('payme', 'payme')], default='progress', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Kutilmoqda', 'Kutilmoqda'), ('Tasdiqlandi', 'Tasdiqlandi'), ('Yuborildi', 'Yuborildi'), ('Yetkazildi', 'Yetkazildi')], default='Kutilmoqda', max_length=100, null=True),
        ),
    ]
