# Generated by Django 3.2.8 on 2021-12-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211219_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Kutilmoqda'), ('2', 'Tasdiqlandi'), ('3', 'Yo`lda'), ('4', 'Buyurtma yetkazildi')], default='Tasdiqlash jarayonida', max_length=100, null=True),
        ),
    ]
